services:
  lifebox_bot:
    build:
      context: .
      dockerfile: Containerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SQLITE_PATH: /data/lifebox.sqlite
    init: true
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - lifebox-sqlite-data:/data

volumes:
  lifebox-sqlite-data:
